### ISSUE TITLE
npm run dev报错是怎么回事

### ISSUE THREAD

**Issue by wangyang19930324** [ADKcodeXD/Myblog-Vue3viteTs#4]
> ADK-Blog@1.0.0 dev
> vite --host

error when starting dev server:
Error: No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package
    at e (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:25)
    at n (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:646)
    at o (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:1297)
    at resolveExportsOrImports (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:28712:20)
    at resolveDeepImport (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:28731:31)
    at tryNodeResolve (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at async file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
    at async file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:44852:20
    at async addManuallyIncludedOptimizeDeps (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:46034:31)
    at async createDepsOptimizer (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:45093:9)
    at async initDepsOptimizer (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:44993:9)
    at async file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:65233:17
    at async Server.httpServer.listen (file:///D:/repository/code/Myblog-Vue3viteTs/node_modules/vite/dist/node/chunks/dep-df561101.js:65247:17)

**Comment by stillNotEthan** [comment]
沒有下載組件包
